name: advent_of_code_2017
description: Advent of Code year 2017
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^1.2.4
  async: ^2.4.2
