name: advent_of_code_2015
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^1.1.1
  crypto: ^2.1.4
  trotter: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
