name: advent_of_code_2021
description: Advent of Code year 2021
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  lints: ^1.0.1
